version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=my_awesome_project.settings.development
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=my_awesome_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A my_awesome_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=my_awesome_project.settings.development

  celery-beat:
    build: .
    command: celery -A my_awesome_project beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=my_awesome_project.settings.development

volumes:
  postgres_data:
  media_volume: